# Use 2 Ingress since the parameter replacement work differently in NGINX for / and /app (see annotation)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ##TF_VAR_prefix##-app-ingress
  annotations:
{%- if language == "apex" %}     
    nginx.ingress.kubernetes.io/rewrite-target: /ords/r/apex_app/apex_app/$2
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: "##ORDS_HOST##"
{%- elif language == "ords" %}     
    nginx.ingress.kubernetes.io/rewrite-target: /ords/starter/module/$2
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: "##ORDS_HOST##"
{%- elif language == "java" and java_framework == "tomcat" %}     
    nginx.ingress.kubernetes.io/rewrite-target: /starter-1.0/$2   
{%- else %}    
    nginx.ingress.kubernetes.io/rewrite-target: /$2    
{%- endif %} 
    # nginx.ingress.kubernetes.io/affinity: "cookie"   
    # nginx.ingress.kubernetes.io/session-cookie-path: "/"    
spec:
  ingressClassName: nginx
{%- if tls == "new_http_01" %}     
  tls:
  - hosts:
    - ##TF_VAR_dns_name##
    secretName: ##TF_VAR_prefix##-tls-secret  
  rules:
    - host: ##TF_VAR_dns_name##
      http:
{%- else %}    
  rules:
    - http:
{%- endif %} 
        paths:
          - path: /##TF_VAR_prefix##/app(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ##TF_VAR_prefix##-app-service
                port:
{%- if language in [ "apex", "ords" ] %}     
                  number: 443
{%- else %}    
                  number: 80
{%- endif %} 
